#!/usr/bin/env python3
"""Stage (iii): layout.json -> prefix.c + common.h + tables + BOLT arguments.

This is the "Gen. Prealloc Code" box in Figure 8. It emits:

  prefix.c          the arena and the <alloc>_wrapper / free_wrapper functions
  common.h          sizes/counts prefix.c needs
  prefix_tables.bin per-slot (counter, offset, size) triples, uint32
  prefix_tables.S   a 3-line .incbin wrapper so the blob links in
  bolt_args.txt     one llvm-bolt argument per line

Why a binary blob: PreFix preallocates *every hot object*, which for a
pointer-chasing benchmark like health is ~1.7 million objects. Emitting that as
C array initialisers would be a ~30 MB source file that takes minutes (and GBs)
to compile; `.incbin` links it instantly.

A wrapper selects an object by *allocation counter*: the Nth call to that
allocator (counting only the call sites BOLT redirects) gets its pre-placed
slot. Slots are stored sorted by counter and consumed in order, so the fast path
is one compare per allocation.

Usage:
    python3 gen_prefix.py --layout layout.json --outdir gen/
"""

from __future__ import annotations

import argparse
import json
import os
import struct

KINDS = ("malloc", "calloc", "realloc")
HEADER = "/* GENERATED by scripts/gen_prefix.py — do not edit by hand. */\n"


def gen_common_h(layout, exc, bases, last, bump_start, align):
    out = [HEADER, "#ifndef PREFIX_COMMON_H\n#define PREFIX_COMMON_H\n\n"]
    out.append(f"#define PREFIX_ARENA_BYTES {layout['arena_bytes']}UL\n")
    out.append(f"#define PREFIX_ALIGN       {align}UL\n")
    out.append(f"#define PREFIX_BUMP_START  {bump_start}UL\n\n")
    for k in KINDS:
        K = k.upper()
        out.append(f"#define PREFIX_{K}_EXC_N     {len(exc.get(k, []))}\n")
        out.append(f"#define PREFIX_{K}_EXC_BASE  {bases.get(k, 0)}\n")
        out.append(f"#define PREFIX_{K}_LAST      {last.get(k, 0)}UL\n")
    out.append("\nextern void *prefix_arena;\n")
    out.append("/* (counter, offset, size) triples for allocations the layout MOVED. */\n")
    out.append("extern const unsigned int prefix_tbl[];\n\n#endif\n")
    return "".join(out)


def split_bump(slots, align, bump_start):
    """Split slots (sorted by counter) into a bump sequence + exceptions.

    Objects placed in allocation order have offsets that are just a running
    cursor, so they need no table entry at all -- the wrapper can bump-allocate
    them. Only objects the layout *moved* (the HDS groups, pulled to the front
    to sit together) become exceptions. This keeps the table a few KB instead of
    tens of MB, which matters: a 19 MB side-table streamed once per allocation
    costs more LLC traffic than the layout saves.
    """
    exceptions, cursor, last = [], bump_start, 0
    for count, offset, size in slots:
        need = (size + align - 1) & ~(align - 1)
        if offset == cursor:
            cursor += need                      # follows the bump sequence
        else:
            exceptions.append((count, offset, size))
        last = max(last, count)
    return exceptions, last


def gen_tables(tables, bases):
    """Pack every kind's EXCEPTION slots into one uint32 blob."""
    blob = bytearray()
    for k in KINDS:
        bases[k] = len(blob) // 12
        for count, offset, size in tables.get(k, []):
            blob += struct.pack("<III", count, offset, size)
    return bytes(blob)


def gen_tables_s():
    return (HEADER +
            '    .section .rodata\n'
            '    .globl prefix_tbl\n'
            '    .align 64\n'
            'prefix_tbl:\n'
            '    .incbin "prefix_tables.bin"\n')


def _wrapper(kind, zero):
    K = kind.upper()
    args = "size_t num, size_t ele" if zero else "size_t size"
    want = "    size_t size = num * ele;\n" if zero else ""
    zero_hit = "            memset(p, 0, size);\n" if zero else ""
    fallback = "calloc(num, ele)" if zero else f"{kind}(size)"
    return f"""void *{kind}_wrapper({args})
{{
{want}    unsigned long i = ++prefix_{kind}_seen;
    if (!prefix_arena)
        return {fallback};

    /* 1. did the layout MOVE this allocation (an HDS member)? */
    unsigned k = prefix_{kind}_exc_slot;
    if (k < PREFIX_{K}_EXC_N) {{
        const unsigned int *e = &prefix_tbl[(PREFIX_{K}_EXC_BASE + k) * 3];
        if (i == e[0]) {{
            prefix_{kind}_exc_slot = k + 1;
            if (size <= e[2]) {{
                void *p = (char *)prefix_arena + e[1];
{zero_hit}                return p;
            }}
        }}
    }}

    /* 2. otherwise keep allocation order -> pure bump, no table read.
     * Deliberately NOT capped at the profiled allocation count: the measured
     * run is longer than the profiling run, and the whole point is that every
     * allocation from these call sites lands in the contiguous arena. We bump
     * until the arena is exhausted, then fall back to the real allocator. */
    {{
        unsigned long c = prefix_cursor;
        unsigned long need = (size + (PREFIX_ALIGN - 1)) & ~(unsigned long)(PREFIX_ALIGN - 1);
        if (c + need <= PREFIX_ARENA_BYTES) {{
            prefix_cursor = c + need;
            void *p = (char *)prefix_arena + c;
{zero_hit}            return p;
        }}
    }}
    return {fallback};
}}

"""


WRAPPER = {"malloc": _wrapper("malloc", False),
           "calloc": _wrapper("calloc", True)}

def gen_prefix_c(layout, tables):
    s = [HEADER, """#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include "common.h"

/* One contiguous arena holding every object PreFix chose to preallocate.
 * Objects sit in HDS / hot-singleton layout order, so co-accessed objects end
 * up adjacent instead of scattered across malloc's free lists. */
void *prefix_arena = NULL;

"""]
    s.append("/* One shared bump cursor: singletons keep allocation order, so their\n"
             " * offsets are just a running cursor -- no per-object table needed. */\n")
    s.append("static unsigned long prefix_cursor = PREFIX_BUMP_START;\n")
    for k in KINDS:
        if tables.get(k):
            s.append(f"static unsigned long prefix_{k}_seen = 0;\n")
            s.append(f"static unsigned prefix_{k}_exc_slot = 0;\n")
    s.append("""
static int prefix_in_arena(const void *p)
{
    return prefix_arena &&
           (uintptr_t)p >= (uintptr_t)prefix_arena &&
           (uintptr_t)p <  (uintptr_t)prefix_arena + PREFIX_ARENA_BYTES;
}

""")
    if tables.get("realloc"):
        s.append("""/* Size of the arena slot a pointer belongs to (0 if not ours).
 * Linear, but only reached when realloc() is called on arena memory. */
static unsigned long prefix_slot_size(const void *p)
{
    if (!prefix_in_arena(p))
        return 0;
    unsigned int off = (unsigned int)((uintptr_t)p - (uintptr_t)prefix_arena);
    for (unsigned i = 0; i < PREFIX_NSLOTS; i++)
        if (prefix_tbl[i * 3 + 1] == off)
            return prefix_tbl[i * 3 + 2];
    return 0;
}

""")
    s.append("""__attribute__((constructor(101))) static void prefix_init(void)
{
    prefix_arena = malloc(PREFIX_ARENA_BYTES);
    if (!prefix_arena) {
        fprintf(stderr, "prefix: arena of %lu bytes failed to allocate\\n",
                (unsigned long)PREFIX_ARENA_BYTES);
        return;
    }
    /* Deliberately NOT memset: malloc does not promise zeroed memory and
     * calloc_wrapper zeroes per object, so eagerly touching the whole arena
     * would just add startup cost. Pages fault in exactly like malloc's would. */
}

__attribute__((destructor(101))) static void prefix_fini(void)
{
    free(prefix_arena);
    prefix_arena = NULL;
}

""")
    for k in KINDS:
        if tables.get(k):
            s.append(WRAPPER[k])
    s.append("""/* Arena pointers must never reach the real free(). */
void free_wrapper(void *ptr)
{
    if (prefix_in_arena(ptr))
        return;
    free(ptr);
}
""")
    return "".join(s)


def gen_bolt_args(layout, tables):
    args = [f"--replace-memalloc={r['func']}:-{r['kind']}"
            for r in layout["redirect"]]
    args.append("--replace-free=enable")   # pass is gated on a non-empty value
    wrappers = [f"{k}_wrapper" for k in KINDS if tables.get(k)] + ["free_wrapper"]
    args.append("--force-inline=" + ",".join(wrappers))
    return "\n".join(args) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--layout", required=True)
    ap.add_argument("--outdir", default="gen")
    args = ap.parse_args()

    with open(args.layout) as f:
        layout = json.load(f)
    objs = layout["objects"]
    if not objs:
        raise SystemExit("layout.json has no objects to place")
    align = int(layout.get("align", 16))

    # Bump region starts where the moved (HDS) objects end.
    bump_start = next((o["offset"] for o in objs if not o.get("hds")),
                      layout["arena_bytes"])

    slots = {}
    for o in objs:
        slots.setdefault(o["kind"], []).append((o["count"], o["offset"], o["size"]))
    for k in slots:
        slots[k].sort(key=lambda e: e[0])

    # The bump fast path needs one shared cursor, so it is only valid when a
    # single allocator feeds the arena. Otherwise every slot becomes an
    # exception (correct, just with the bigger table).
    exc, last = {}, {}
    if len(slots) == 1:
        k = next(iter(slots))
        exc[k], last[k] = split_bump(slots[k], align, bump_start)
    else:
        for k, v in slots.items():
            exc[k], last[k] = list(v), 0

    bases = {}
    blob = gen_tables(exc, bases)

    os.makedirs(args.outdir, exist_ok=True)
    out = {
        "common.h": gen_common_h(layout, exc, bases, last, bump_start, align),
        "prefix.c": gen_prefix_c(layout, slots),
        "prefix_tables.S": gen_tables_s(),
        "bolt_args.txt": gen_bolt_args(layout, slots),
    }
    for name, text in out.items():
        with open(os.path.join(args.outdir, name), "w") as f:
            f.write(text)
    with open(os.path.join(args.outdir, "prefix_tables.bin"), "wb") as f:
        f.write(blob)

    n_exc = sum(len(v) for v in exc.values())
    print(f"[gen_prefix] arena {layout['arena_bytes']/1048576.0:.1f} MB, "
          f"{len(objs)} slots: {n_exc} moved (table {len(blob)/1024.0:.1f} KB) + "
          f"{len(objs) - n_exc} bump-allocated")
    for r in layout["redirect"]:
        print(f"[gen_prefix] BOLT will redirect {r['kind']}() calls in {r['func']}()")
    print(f"[gen_prefix] wrote prefix.c, common.h, prefix_tables.{{S,bin}}, "
          f"bolt_args.txt in {args.outdir}")


if __name__ == "__main__":
    main()
